# Site settings
title: Castle Point Anime Convention
email: info@castlepointanime.com
description: >
  Castle Point Anime Convention is run by Stevens' Anime Club and
  student volunteers. It has been a yearly event since it started
  Spring 2008.
baseurl: ""
url: "http://www.castlepointanime.com"

paginate: 5
paginate_path: "news/page:num/index.html"

# Build settings
markdown: kramdown
exclude:
  - Gemfile
  - Gemfile.lock
  - .env
  - s3_website.yml
